services:
  app:
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    networks:
      - userscrud-network
  mysql-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=jdbc:mysql://localhost:3306/USER_DATABASE
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    ports:
      - 3306:3306
    networks:
      - userscrud-network
networks:
  userscrud-network:
    driver: bridge